### ISSUE TITLE
Every project should have its own repository

### ISSUE THREAD

**Issue by Tereseus** [seangnewman/PersonalDevelopment#1]
I understand as you why you might want to keep everything together in one directory on your desktop but on github having multiple projects in the same repo is very difficult for someone else to clone, pull, push to etc. Every project on github should have its own repository. I know it can lead up to having 100's of repos but it makes it far easier for others to look and help work on code especially since many projects require readme for quick references. If there are certain projects you do not want other people to see you can always make them private. I don't even know if you can do that for certain folders if you have it all in one repository?

Just something you will run into in the future.

**Comment by seangnewman** [comment]
Complete.. pushed to https://github.com/seangnewman/Codecademy-jammming
