### ISSUE TITLE
Public folder & Index.html - Jamming

### ISSUE THREAD

**Issue by Tereseus** [seangnewman/PersonalDevelopment#2]
When I tried to run your repository I was unable to find index.html because node is looking for public/index.html. The public folder does not exist so I am unable to load your repository. Also your index.html is empty, the only think you have in there is "Start", your index.html should at least have:

`<div id="root"></div>`

Which your app should render to.

I would suggest getting the index.html from the starter files to be able to continue the project.

**Comment by seangnewman** [comment]
Completed... https://github.com/seangnewman/Codecademy-jammming
