### ISSUE TITLE
Summary - Unable to continue - Jamming

### ISSUE THREAD

**Issue by Tereseus** [seangnewman/PersonalDevelopment#3]
There were to many issues for me to continue to work on your project. How did you test your project exactly? The lack of some files prevented me from even fully testing multiple aspects of it. 

Did you perhaps accidently delete some things? This issue might have been caused by having multiple projects on github, perhaps the other files were not added correctly? 

Many of these issues are relatively simple and I see that most if not all of your code in your components and spotify.js look right so there must have been some type of mistake with git. Once you fix these small issues resubmit your project for review.

If you require help feel free to contact the advisors, we can guide you through the project.

**Comment by seangnewman** [comment]
Pushed the entire project to repository
